jobs:
  test-and-release:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Wait until postgres is ready before test steps run.
        # See https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Test package
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost
